// This file is generated by Slice Machine. Update with care!

import AdsBigBanner from './AdsBigBanner';
import FaqList from './FaqList';
import FeaturesSection from './FeaturesSection';
import HeroParagraph from './HeroParagraph';
import HeroSection from './HeroSection';
import IntroVideo from './IntroVideo';
import OurJourneySection from './OurJourneySection';
import OurTeam from './OurTeam';
import QuotesSection from './QuotesSection';
import StepsSection from './StepsSection';

export {
	AdsBigBanner,
	FaqList,
	FeaturesSection,
	HeroParagraph,
	HeroSection,
	IntroVideo,
	OurJourneySection,
	OurTeam,
	QuotesSection,
	StepsSection,
};

export const components = {
	ads_big_banner: AdsBigBanner,
	faq_list: FaqList,
	features_section: FeaturesSection,
	hero_paragraph: HeroParagraph,
	hero_section: HeroSection,
	intro_video: IntroVideo,
	our_journey_section: OurJourneySection,
	our_team: OurTeam,
	quotes_section: QuotesSection,
	steps_section: StepsSection,
};
